
modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
logoFile = "better_deco_logo_4.png"
displayURL="https://github.com/TearPelato/BetterDeco"
credits = "LiukRast, BlackGear"
updateJSONURL="https://tearpelato.github.io/BetterDeco/version-check-nf.json"

[[accessTransformers]]
file ="META-INF/accesstransformer.cfg"

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[modproperties."${mod_id}"]
catalogueImageIcon = "assets/better_deco/icon.png"
catalogueBackground = "assets/better_deco/background.png"